### ISSUE TITLE
model url broken

### ISSUE THREAD

**Issue by justheuristic** [masashi-y/depccg#10]
Hi!
(and thanks for the awesome framework)

There seems to be a problem with the base model download url,
http://cl.naist.jp/~masashi-y/resources/depccg/en_hf_tri.tar.gz

I can't access it from any location i can reach (europe, us, russia).
Is there an alternative link i can use?

**Comment by masashi-y** [comment]
Sorry for the incovenience!
I am looking for somewhere else to place my files.
I tantatively place them on Google drive. Please download them from the following links.
(`depccg_en download` does not work now.)

Japanese default model: https://drive.google.com/file/d/1bblQ6FYugXtgNNKnbCYgNfnQRkBATSY3/view?usp=sharing
English default model (en_hf_tri.tar.gz): https://drive.google.com/file/d/1mxl1HU99iEQcUYhWhvkowbE4WOH0UKxv/view?usp=sharing
English ELMo model: https://drive.google.com/file/d/1UldQDigVq4VG2pJx9yf3krFjV0IYOwLr/view?usp=sharing
tri-training dataset: https://drive.google.com/file/d/1rCJyb98AcNx5eBuC18-koCWJFfU4OV06/view?usp=sharing

**Comment by justheuristic** [comment]
Thank you! It seems to work now

As a potential alternative, you may want to consider dropbox, as it allows for direct download links
Once you create file share url, like this
https://www.dropbox.com/s/eeatdplp3lxrnbp/decaf1M256_learn.fvecs?dl=0

you can download it with, for example, 
wget https://www.dropbox.com/s/eeatdplp3lxrnbp/decaf1M256_learn.fvecs?dl=1 -O decaf1M256_learn.fvecs

Note the dl=1 flag there

**Comment by masashi-y** [comment]
Oooh thank you for the kind suggestion!
but I decided to go on with Google drive and just wrote codes for enabling `python -m depccg en download`, by using `googledrivedownloader` python library.
If this does not go well, I'll try your idea:)

**Comment by justheuristic** [comment]
(and i will, in turn, try google drive downloader for my projects, thank you :+1: )
