### ISSUE TITLE
vocab URL broken

### ISSUE THREAD

**Issue by attrn** [masashi-y/depccg#14]
Hello,

Thank you so much for sharing your work.

I notice that the URL for vocab seems to be broken: http://cl.naist.jp/~masashi-y/resources/depccg/vocabulary.tar.gz

Could you provide an alternative link?

Thank you again for your help.

**Comment by masashi-y** [comment]
I'm sorry I didn't notice the issue. I uploaded the file here: https://drive.google.com/file/d/1_rX5UAxVjjcXpRM6EoWee4XprYjEonwl/view?usp=sharing
The link is fixed too.
