### ISSUE TITLE
Never-ending installation

### ISSUE THREAD

**Issue by helloerikaaa** [masashi-y/depccg#27]
Last night I tried to install the package using pipenv with the command `pipenv install depccg --verbose,` but it's taking forever to install, I tried the `--verbose` argument to see some logs, but the only log I got was: 

`Installing package: depccg`

`Writing supplied requirement line to temporary file: 'depccg'`

It's been more than 15 hours and the console keep logging the message: `⠧ Installing depccg...`

My hardware is:
- MacBook Pro, Intel i5, macOS Monterey

**Comment by masashi-y** [comment]
Thank you for the report. I previously had no problem installing depccg on macOS Big Sur (with Intel CPU) but haven't tried on Monterey yet.
In most cases, an issue in installing depccg involves building C++ part of the code, which is done by the following.
Could you let me know what would happen when doing the following?
If fails, could you let me know the version of the used C++ compiler, too? (I expect that g++ 4.8 or above should work..)

```sh
$ git clone https://github.com/masashi-y/depccg
$ cd depccg
$ python setup.py build_ext --inplace  # build
$ python setup.py install  # if the above successes, you can install by this
```

**Comment by helloerikaaa** [comment]
Thank you for your response. I'm using Apple's clang package with version 13.0.0, also I checked and Xcode command line tools are installed on my computer.  I tried the solution you're suggesting, but now I got this log:

`depccg/parsing.cpp:12804:16: warning: absolute value function 'abs' given an argument of type 'const Py_ssize_t' (aka 'const long') but has parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
    if (likely(__Pyx_sst_abs(size) <= 1)) {
               ^
depccg/parsing.cpp:698:34: note: expanded from macro '__Pyx_sst_abs'
    #define __Pyx_sst_abs(value) std::abs(value)
                                 ^
depccg/parsing.cpp:12804:16: note: use function 'std::abs' instead
depccg/parsing.cpp:698:34: note: expanded from macro '__Pyx_sst_abs'
    #define __Pyx_sst_abs(value) std::abs(value)
                                 ^
depccg/parsing.cpp:12804:16: note: include the header <cstdlib> or explicitly provide a declaration for 'std::abs'
depccg/parsing.cpp:698:34: note: expanded from macro '__Pyx_sst_abs'
    #define __Pyx_sst_abs(value) std::abs(value)
                                 ^
224 warnings and 13 errors generated.
error: command 'clang' failed with exit status 1`

Sounds like the problem it's on Apple's side because of the clang package, but still not sure.

**Comment by masashi-y** [comment]
I got a chance to use Monterey (on Intel CPU) and tested installing depccg with success (though with a bit of ignorable warnings). Is there any difference from my environment below?
Or it may have something to do with Cython. Could you try reinstalling it by following and try the above again?

```sh
$ pip install -U cython
$ python setup.py clean  # in the cloned depccg folder
$ python setup.py build_ext --inplace
```

- clang 13.0.0
- Python 3.8
- Cython 0.29.16
