### ISSUE TITLE
”pip install depccg” fails with an error

### ISSUE THREAD

**Issue by Ayumu-walker** [masashi-y/depccg#28]
Hi.
I get the following error message when I try to install depccg. How should I deal with this?
"Releases" is empty, does this have anything to do with it?

pip install depccg
↓
Collecting depccg
  Using cached depccg-2.0.2.tar.gz (3.5 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\XXXXX\anaconda3\envs\qiskit\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\XXXXXXXXX\\AppData\\Local\\Temp\\pip-install-l1bjgvy2\\depccg_1e7b5a90f22840b7aaf4447c64be1c3e\\setup.py'"'"'; __file__='"'"'C:\\Users\\XXXXXX\\AppData\\Local\\Temp\\pip-install-l1bjgvy2\\depccg_1e7b5a90f22840b7aaf4447c64be1c3e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\XXXXXXXX\AppData\Local\Temp\pip-pip-egg-info-2c1_az10'
       cwd: C:\Users\XXXXXXX\AppData\Local\Temp\pip-install-l1bjgvy2\depccg_1e7b5a90f22840b7aaf4447c64be1c3e\
  Complete output (13 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\XXXXXXXX\AppData\Local\Temp\pip-install-l1bjgvy2\depccg_1e7b5a90f22840b7aaf4447c64be1c3e\setup.py", line 105, in <module>
      generate_cpp([])
    File "C:\Users\XXXXXXXXX\AppData\Local\Temp\pip-install-l1bjgvy2\depccg_1e7b5a90f22840b7aaf4447c64be1c3e\setup.py", line 62, in generate_cpp
      p = subprocess.call(["make", options], env=os.environ)
    File "c:\users\XXXXXXXXXX\anaconda3\envs\qiskit\lib\subprocess.py", line 340, in call
      with Popen(*popenargs, **kwargs) as p:
    File "c:\users\XXXXXXXXXX\anaconda3\envs\qiskit\lib\subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "c:\users\XXXXXXXXXX\anaconda3\envs\qiskit\lib\subprocess.py", line 1311, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a9/92/8f3b372662f63e0c4af3cbad41daffeeb6d0df496dc64e7f843a66d55016/depccg-2.0.2.tar.gz#sha256=de1a7ce6a9d707a2a8dc5c0730ed2d435694d4c297e747a8c9a6c329cc4438a4 (from https://pypi.org/simple/depccg/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by masashi-y** [comment]
Hi, sorry that I reply late.
Currently using depccg on Windows is not supported. Could you consider using it on WSL?
