### ISSUE TITLE
depccg_ja downloadでエラー

### ISSUE THREAD

**Issue by ghost** [masashi-y/depccg#29]
google colabにてdepccgを使用させていただいております。
昨年(2021年12月ごろ)までは問題なく使用できていたのですが、先日(2022年2月)、下記コマンドでインストールした際、
pip install cython numpy depccg
インストールは行えたのですが、depccg_ja downloadでエラーが発生してしまいました。
最初はimport errorのNo module named 'overrides'であったためoverridesをインストールし、
次にimport errorのno module named 'google.cloud.storage.retry'であったためgoogle-cloud-storageをアップグレードしたところ、

TypeError: JaSupertaggingDatasetReader._read: return type `None` is not a `typing.Iterable[allennlp.data.instance.Instance]`.

のエラーが発生しました。本エラーを回避する方法があればお教えいただきたく存じます。

**Comment by masashi-y** [comment]
問題についてお教えいただきありがとうございます。最新のoverridesを使うと、overrideするメンバー関数のインターフェースが厳密に親クラスのものと一致しているかを確認するようになったようなのですが、実際のところ僕は厳密にそのように実装していない点が問題になってしまったようでした (AllenNLPの方針に倣いoverridesを使うのをやめました)。
それ以外にも関連して少しupdateが遅れている箇所が見つかったため、いくらか修正を施し最新のものをPyPIに登録しましたので、おそらく`pip install cython numpy depccg`からやり直せば問題なく動くのではないかと期待しております。
また他にも問題が起こりましたらぜひお教えください。

**Comment by ghost** [comment]
早速の対応ありがとうございます。
しかし、google colabでpip install cython numpy depccgからやり直したところ、同じようなエラーをはかれてしまいました。
そこでgoogle colab内でソースコードを見たところ、updateが反映されていなかった(まだdepccg/allennlp/dataset/ja_supertagging_dataset.pyが残っていた)ため、google colab側の問題の可能性があり、同じような問題が無いか調べてみることにします。
お忙しいところ対応していただき、ありがとうございました。

**Comment by masashi-y** [comment]
もし前にpipしたものが残っているような環境であれば、`pip install -U cython numpy depccg`のようなオプションをつけたほうがいいかもしれません？

**Comment by ghost** [comment]
ありがとうございます。
google colabはデフォルトで入っているライブラリ以外は起動するたびにリセットされているため、残っていることは無いと思います。
pip install -U cython numpy depccgを試したところ、やはりfrom overrides import overridesが残ったままでした...

**Comment by masashi-y** [comment]
すみません、こちらの件僕のミスだったようで、新しいバージョンをPyPIに登録するところで手違いがありました。修正しましたので最新のものは大丈夫なはずです！

**Comment by ghost** [comment]
ありがとうございます。
試してみたところ、No module named 'google.cloud.storage.retry'　は再度出たため pip install --upgrade google-cloud-storage を行った結果、無事depccg_ja downloadができ、正常な動作を確認できました！
この度はお忙しいところ迅速な対応をしていただきありがとうございました。
