### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by AAMIBhavya** [masashi-y/depccg#3]
Hi,
I am accessing _depccg_ from Python. When I call the function _res = parser.parse("this is a test sentence")_  It gives an error

>   File "<stdin>", line 1, in <module>
>   File "depccg.pyx", line 602, in depccg.PyAStarParser.parse
>     assert isinstance(sent, unicode)
> AssertionError

What may be causing this error? (Just for an experimentation I tried change the command to _res = parser.parse(unicode("this is a test sentence"))_ but it is giving error in another place)

**Comment by masashi-y** [comment]
Hi. Thank you for using my program!
My implementation expects the input to be unicode (python 2) or str (python 3)
so parser.parse(unicode(...)) is the right way of using it.

The error in another place should be the problem I should fix.
Could you tell me about it in detail?

**Comment by AAMIBhavya** [comment]
Hi,
Thank you for your quick reply.
When I tried parser.parse(unicode(...)), I am getting the following error (I am using Python 2.7)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "depccg.pyx", line 609, in depccg.PyAStarParser.parse
    [mat] = self.py_tagger.predict([splitted])
  File "py/lstm_parser_bi_fast.py", line 200, in predict
    cat_ys, dep_ys = self.forward(ws, ss, ps, ls)
  File "py/lstm_parser_bi_fast.py", line 157, in forward
    ins = F.dropout(F.concat([wss, sss, pss], 2), self.dropout_ratio, train=self.train)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/noise/dropout.py", line 68, in dropout
    kwargs, train='train argument is not supported anymore. '
  File "/usr/local/lib/python2.7/dist-packages/chainer/utils/argument.py", line 4, in check_unexpected_kwargs
    raise ValueError(message)
ValueError: train argument is not supported anymore. Use chainer.using_config


Thanks

**Comment by AAMIBhavya** [comment]
Resolved this!

It seems that this project used chainer v 1.x. I was running chainer v2.
The train argument has been depricated in v2.

Thanks!

**Comment by masashi-y** [comment]
Sorry for the inconvenience.

Yes, I was using the older version of chainer and
didn't update the program according to the latest version of it.

I updated README and added the required chainer version.
Thank you for your help!
