### ISSUE TITLE
Query of notation meanings

### ISSUE THREAD

**Issue by itlchriss** [masashi-y/depccg#32]
Dear [Author],

   I am trying to use the tool as a component in my research. May I know the meanings of the notations in the result? 
Precisely, I have noticed notations such as Subj(), Acc(), AccI etc. May I have the explanations of their meanings?

Thanks and Best Regards,
Sincerely,
Chriss IT. Leong

**Comment by masashi-y** [comment]
Hi, thank you for using depccg! The semantic parsing component is actually developed at https://github.com/mynlp/ccg2lambda, and we just call its interface.
The details are available in that repo, or for the notation specifically, its based on event semantics and maybe the following paper should be referred.
https://aclanthology.org/E17-1067.pdf
