### ISSUE TITLE
N-best output format slightly different to that of EasyCCG

### ISSUE THREAD

**Issue by pasmargo** [masashi-y/depccg#6]
In EasyCCG, when I request N-best parsing for one sentence, I get something like this:

```
ID=1
(<T ... 1-best parse of the first sentence ... )
ID=1
(<T ... 2-best parse of the first sentence ... )
```

However, in depccg we obtain something like this:

```
ID=0
score= ...
(<T ... 1-best parse of the first sentence ... )
(<T ... 2-best parse of the first sentence ... )
```

It would be great to have the same format as EasyCCG (ID starting from 1, repeat ID for every new parse, and produce no scores). Do you have plans to adjust this format to be compatible with pipelines that already use EasyCCG N-best parsing?

**Comment by masashi-y** [comment]
Hi!
I agree the format should be compatible.
I updated accordingly and hope you'll like!

**Comment by pasmargo** [comment]
Thank you!!
